// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDRVLd8M8QmSlPS061Yxz-8TS9u9uqPMyM',
    appId: '1:938771276348:web:81e90a30b7cf9bc1405939',
    messagingSenderId: '938771276348',
    projectId: 'elearning-36a1b',
    authDomain: 'elearning-36a1b.firebaseapp.com',
    storageBucket: 'elearning-36a1b.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCAPcCXRmAPNFYOBaf-kGKzzblGDUY0HIA',
    appId: '1:938771276348:android:2fd23122c0cb6119405939',
    messagingSenderId: '938771276348',
    projectId: 'elearning-36a1b',
    storageBucket: 'elearning-36a1b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC64K_YNICnI6GDg6JVOCTAE4fRS77O080',
    appId: '1:938771276348:ios:7b14af568cca9fb7405939',
    messagingSenderId: '938771276348',
    projectId: 'elearning-36a1b',
    storageBucket: 'elearning-36a1b.appspot.com',
    iosBundleId: 'com.example.elearning',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC64K_YNICnI6GDg6JVOCTAE4fRS77O080',
    appId: '1:938771276348:ios:7b14af568cca9fb7405939',
    messagingSenderId: '938771276348',
    projectId: 'elearning-36a1b',
    storageBucket: 'elearning-36a1b.appspot.com',
    iosBundleId: 'com.example.elearning',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDRVLd8M8QmSlPS061Yxz-8TS9u9uqPMyM',
    appId: '1:938771276348:web:795614d2a128c7d3405939',
    messagingSenderId: '938771276348',
    projectId: 'elearning-36a1b',
    authDomain: 'elearning-36a1b.firebaseapp.com',
    storageBucket: 'elearning-36a1b.appspot.com',
  );
}
